version: '3'

services:
  # grafana used for graphing postgis data
  grafana:
    container_name: thredds.grafana
    image: grafana/grafana
    user: ${UID}
    restart: always
    ports:
    - '3001:3000'
    volumes:
    - ./volumes/grafana-volumes/lib:/var/lib/grafana
#    - ./docker/grafana-volumes/etc:/etc/grafana
    - ./dist:/var/lib/grafana/plugins/thredds
#    environment:
#      GF_INSTALL_PLUGINS: 'percona-percona-app,citilogics-geoloop-panel,grafana-worldmap-panel'
#      GF_SECURITY_ADMIN_PASSWORD: '${GF_SECURITY_ADMIN_PASSWORD}'
#      GF_SECURITY_SECRET_KEY: '${GF_SECURITY_SECRET_KEY}'
#      GF_USERS_ALLOW_SIGN_UP: 'false'
#      GF_SERVER_ROOT_URL: '${GF_SERVER_ROOT_URL}'
#      GF_SMTP_PASSWORD: '${GF_SMTP_PASSWORD}'
#    depends_on:
#    - postgis